### ISSUE TITLE
Add syntax highlight option to `report` action

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#56]
We have discussed this a few times -- when we want to write something like a `utility.py` that can be sourced and used in a number of steps we can achieve it by using a `report` step to edit  them in the SoS script and generate this file on the fly. Is that still the recommended practice?

In that case, it would be helpful to be able to tell `report` what kind of script we are generating, so it can choose the correct syntax highlighting. Currently I have to edit eg Python code like this:

![image](https://user-images.githubusercontent.com/917985/84042072-9e92ad00-a972-11ea-94f5-d0c3aa953b84.png)

which does not look very nice.

**Comment by BoPeng** [comment]
@gaow Released jupyterlab-sos 0.6.5. I will wait for your confirmation before porting to classic jupyter.

**Comment by gaow** [comment]
@BoPeng Thank you! I confirm that hard-coded name works:

![image](https://user-images.githubusercontent.com/917985/88796633-f9c16e80-d16f-11ea-9722-5c457c25cf08.png)

But not with f-string:

![image](https://user-images.githubusercontent.com/917985/88796459-acdd9800-d16f-11ea-973a-2c03ae8b9bdd.png)

> This of course requires that the filename is hardcoded (not variable), but should cover 99% of the cases.

I thought we cannot do `output = filename` but can do `output=f'{filename}.py'` ...

**Comment by BoPeng** [comment]
OK. I fixed that.

The problem with `report` is that it is not 'code', so there is a much wide range of possible formats such as html, yaml, json, even tex. I have added `html/xml`, `yaml/json`, and  `tex` but not all. The problem is that currently these modules are loaded statically (all of them), not dynamically depending on format, so they have a negative impact on page loading speed.

version 0.6.7 was released. Please try again.

**Comment by gaow** [comment]
Thanks it works now! I dont see noticeable difference in terms of page rendering.
